import Foundation

public enum X11Color: String {
    case aliceblue, antiquewhite, antiquewhite1, antiquewhite2, antiquewhite3
    case antiquewhite4, aquamarine, aquamarine1, aquamarine2, aquamarine3
    case aquamarine4, azure, azure1, azure2, azure3
    case azure4, beige, bisque, bisque1, bisque2
    case bisque3, bisque4, black, blanchedalmond, blue
    case blue1, blue2, blue3, blue4, blueviolet
    case brown, brown1, brown2, brown3, brown4
    case burlywood, burlywood1, burlywood2, burlywood3, burlywood4
    case cadetblue, cadetblue1, cadetblue2, cadetblue3, cadetblue4
    case chartreuse, chartreuse1, chartreuse2, chartreuse3, chartreuse4
    case chocolate, chocolate1, chocolate2, chocolate3, chocolate4
    case coral, coral1, coral2, coral3, coral4
    case cornflowerblue, cornsilk, cornsilk1, cornsilk2, cornsilk3
    case cornsilk4, crimson, cyan, cyan1, cyan2
    case cyan3, cyan4, darkgoldenrod, darkgoldenrod1, darkgoldenrod2
    case darkgoldenrod3, darkgoldenrod4, darkgreen, darkkhaki, darkolivegreen
    case darkolivegreen1, darkolivegreen2, darkolivegreen3, darkolivegreen4, darkorange
    case darkorange1, darkorange2, darkorange3, darkorange4, darkorchid
    case darkorchid1, darkorchid2, darkorchid3, darkorchid4, darksalmon
    case darkseagreen, darkseagreen1, darkseagreen2, darkseagreen3, darkseagreen4
    case darkslateblue, darkslategray, darkslategray1, darkslategray2, darkslategray3
    case darkslategray4, darkslategrey, darkturquoise, darkviolet, deeppink
    case deeppink1, deeppink2, deeppink3, deeppink4, deepskyblue
    case deepskyblue1, deepskyblue2, deepskyblue3, deepskyblue4, dimgray
    case dimgrey, dodgerblue, dodgerblue1, dodgerblue2, dodgerblue3
    case dodgerblue4, firebrick, firebrick1, firebrick2, firebrick3
    case firebrick4, floralwhite, forestgreen, gainsboro, ghostwhite
    case gold, gold1, gold2, gold3, gold4
    case goldenrod, goldenrod1, goldenrod2, goldenrod3, goldenrod4
    case gray, gray0, gray1, gray10, gray100
    case gray11, gray12, gray13, gray14, gray15
    case gray16, gray17, gray18, gray19, gray2
    case gray20, gray21, gray22, gray23, gray24
    case gray25, gray26, gray27, gray28, gray29
    case gray3, gray30, gray31, gray32, gray33
    case gray34, gray35, gray36, gray37, gray38
    case gray39, gray4, gray40, gray41, gray42
    case gray43, gray44, gray45, gray46, gray47
    case gray48, gray49, gray5, gray50, gray51
    case gray52, gray53, gray54, gray55, gray56
    case gray57, gray58, gray59, gray6, gray60
    case gray61, gray62, gray63, gray64, gray65
    case gray66, gray67, gray68, gray69, gray7
    case gray70, gray71, gray72, gray73, gray74
    case gray75, gray76, gray77, gray78, gray79
    case gray8, gray80, gray81, gray82, gray83
    case gray84, gray85, gray86, gray87, gray88
    case gray89, gray9, gray90, gray91, gray92
    case gray93, gray94, gray95, gray96, gray97
    case gray98, gray99, green, green1, green2
    case green3, green4, greenyellow, grey, grey0
    case grey1, grey10, grey100, grey11, grey12
    case grey13, grey14, grey15, grey16, grey17
    case grey18, grey19, grey2, grey20, grey21
    case grey22, grey23, grey24, grey25, grey26
    case grey27, grey28, grey29, grey3, grey30
    case grey31, grey32, grey33, grey34, grey35
    case grey36, grey37, grey38, grey39, grey4
    case grey40, grey41, grey42, grey43, grey44
    case grey45, grey46, grey47, grey48, grey49
    case grey5, grey50, grey51, grey52, grey53
    case grey54, grey55, grey56, grey57, grey58
    case grey59, grey6, grey60, grey61, grey62
    case grey63, grey64, grey65, grey66, grey67
    case grey68, grey69, grey7, grey70, grey71
    case grey72, grey73, grey74, grey75, grey76
    case grey77, grey78, grey79, grey8, grey80
    case grey81, grey82, grey83, grey84, grey85
    case grey86, grey87, grey88, grey89, grey9
    case grey90, grey91, grey92, grey93, grey94
    case grey95, grey96, grey97, grey98, grey99
    case honeydew, honeydew1, honeydew2, honeydew3, honeydew4
    case hotpink, hotpink1, hotpink2, hotpink3, hotpink4
    case indianred, indianred1, indianred2, indianred3, indianred4
    case indigo, invis, ivory, ivory1, ivory2
    case ivory3, ivory4, khaki, khaki1, khaki2
    case khaki3, khaki4, lavender, lavenderblush, lavenderblush1
    case lavenderblush2, lavenderblush3, lavenderblush4, lawngreen, lemonchiffon
    case lemonchiffon1, lemonchiffon2, lemonchiffon3, lemonchiffon4, lightblue
    case lightblue1, lightblue2, lightblue3, lightblue4, lightcoral
    case lightcyan, lightcyan1, lightcyan2, lightcyan3, lightcyan4
    case lightgoldenrod, lightgoldenrod1, lightgoldenrod2, lightgoldenrod3, lightgoldenrod4
    case lightgoldenrodyellow, lightgray, lightgrey, lightpink, lightpink1
    case lightpink2, lightpink3, lightpink4, lightsalmon, lightsalmon1
    case lightsalmon2, lightsalmon3, lightsalmon4, lightseagreen, lightskyblue
    case lightskyblue1, lightskyblue2, lightskyblue3, lightskyblue4, lightslateblue
    case lightslategray, lightslategrey, lightsteelblue, lightsteelblue1, lightsteelblue2
    case lightsteelblue3, lightsteelblue4, lightyellow, lightyellow1, lightyellow2
    case lightyellow3, lightyellow4, limegreen, linen, magenta
    case magenta1, magenta2, magenta3, magenta4, maroon
    case maroon1, maroon2, maroon3, maroon4, mediumaquamarine
    case mediumblue, mediumorchid, mediumorchid1, mediumorchid2, mediumorchid3
    case mediumorchid4, mediumpurple, mediumpurple1, mediumpurple2, mediumpurple3
    case mediumpurple4, mediumseagreen, mediumslateblue, mediumspringgreen, mediumturquoise
    case mediumvioletred, midnightblue, mintcream, mistyrose, mistyrose1
    case mistyrose2, mistyrose3, mistyrose4, moccasin, navajowhite
    case navajowhite1, navajowhite2, navajowhite3, navajowhite4, navy
    case navyblue, none, oldlace, olivedrab, olivedrab1
    case olivedrab2, olivedrab3, olivedrab4, orange, orange1
    case orange2, orange3, orange4, orangered, orangered1
    case orangered2, orangered3, orangered4, orchid, orchid1
    case orchid2, orchid3, orchid4, palegoldenrod, palegreen
    case palegreen1, palegreen2, palegreen3, palegreen4, paleturquoise
    case paleturquoise1, paleturquoise2, paleturquoise3, paleturquoise4, palevioletred
    case palevioletred1, palevioletred2, palevioletred3, palevioletred4, papayawhip
    case peachpuff, peachpuff1, peachpuff2, peachpuff3, peachpuff4
    case peru, pink, pink1, pink2, pink3
    case pink4, plum, plum1, plum2, plum3
    case plum4, powderblue, purple, purple1, purple2
    case purple3, purple4, red, red1, red2
    case red3, red4, rosybrown, rosybrown1, rosybrown2
    case rosybrown3, rosybrown4, royalblue, royalblue1, royalblue2
    case royalblue3, royalblue4, saddlebrown, salmon, salmon1
    case salmon2, salmon3, salmon4, sandybrown, seagreen
    case seagreen1, seagreen2, seagreen3, seagreen4, seashell
    case seashell1, seashell2, seashell3, seashell4, sienna
    case sienna1, sienna2, sienna3, sienna4, skyblue
    case skyblue1, skyblue2, skyblue3, skyblue4, slateblue
    case slateblue1, slateblue2, slateblue3, slateblue4, slategray
    case slategray1, slategray2, slategray3, slategray4, slategrey
    case snow, snow1, snow2, snow3, snow4
    case springgreen, springgreen1, springgreen2, springgreen3, springgreen4
    case steelblue, steelblue1, steelblue2, steelblue3, steelblue4
    case tan, tan1, tan2, tan3, tan4
    case thistle, thistle1, thistle2, thistle3, thistle4
    case tomato, tomato1, tomato2, tomato3, tomato4
    case transparent, turquoise, turquoise1, turquoise2, turquoise3
    case turquoise4, violet, violetred, violetred1, violetred2
    case violetred3, violetred4, wheat, wheat1, wheat2
    case wheat3, wheat4, white, whitesmoke, yellow
    case yellow1, yellow2, yellow3, yellow4, yellowgreen
}
